#  What hidden patterns exist in customer purchasing behavior?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

##1. The Loyalty & "Value" Discovery

In [8]:
user_infos=pd.read_csv('/content/dim_users.csv')
user_infos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22955 entries, 0 to 22954
Data columns (total 41 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         22955 non-null  int64
 1   user_id                    22944 non-null  float64
 2   created                    22955 non-null  int64
 3   updated                    22955 non-null  int64
 4   account_closure_requested  22955 non-null  int64
 5   age_group_id               104 non-null    float64
 6   app_version                349 non-null    float64
 7   area_id                    7 non-null      float64
 8   cltv                       22955 non-null  float64
 9   country                    22955 non-null  object
 10  currency                   22955 non-null  object
 11  date_of_birth              119 non-null    float64
 12  do_not_contact             22955 non-null  int64
 13  first_name                 22955 non-null  object
 14  gender_id                  224 non-null    float64
 15  last_name                  22955 non-null  object
 16  mobile_phone               22955 non-null  int64
 17  picture                    22944 non-null  object
 18  orders                     22955 non-null  int64
 19  redeemed_points            22955 non-null  int64
 20  referring_user_id          0 non-null      float64
 21  referring_place_id         568 non-null    float64
 22  savings                    22955 non-null  float64
 23  source                     6 non-null      object
 24  type                       22955 non-null  object
 25  api_key                    22954 non-null  object
 26  roles                      22955 non-null  object
 27  email                      22955 non-null  object
 28  password                   3630 non-null   object
 29  referral_id                22945 non-null  float64
 30  otp                        20870 non-null  float64
 31  language                   22944 non-null  object
 32  email_temp                 98 non-null     object
 33  mobile_phone_temp          17284 non-null  float64
 34  mobile_phone_valid         22955 non-null  int64
 35  email_valid                22955 non-null  int64
 36  barcode_scanner_ids        4 non-null      object
 37  receipt_printer_ids        1340 non-null   object
 38  payment_terminal_ids       1219 non-null   object
 39  notifications              22923 non-null  object
 40  favorite_place_ids         73 non-null     object
dtypes: float64(13), int64(10), object(18)
memory usage: 7.2+ MB

/tmp/ipython-input-800201992.py:1: DtypeWarning: Columns (36,40) have mixed types. Specify dtype option on import or set low_memory=False.
  user_infos=pd.read_csv('/content/dim_users.csv')

In [15]:
user_infos["savings"]

0           0.0
1           0.0
2        2640.0
3           0.0
4           9.0
          ...
22950       0.0
22951       0.0
22952       0.0
22953       0.0
22954       0.0
Name: savings, Length: 22955, dtype: float64

In [16]:
user_infos[user_infos["savings"]==0.0]

,id,user_id,created,updated,account_closure_requested,age_group_id,app_version,area_id,cltv,country,...,language,email_temp,mobile_phone_temp,mobile_phone_valid,email_valid,barcode_scanner_ids,receipt_printer_ids,payment_terminal_ids,notifications,favorite_place_ids
0,0,0.0,1571676937,1605685627,0,NaN,NaN,NaN,0.0,DK,...,en,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,1571676937,1744002851,0,12033.0,NaN,11470.0,232.0,DK,...,en,NaN,NaN,0,0,NaN,NaN,NaN,push_orders|push_others|email_orders|email_others,NaN
3,423,423.0,1610598865,1744002851,0,NaN,NaN,NaN,0.0,DK,...,en,NaN,NaN,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
5,425,425.0,1610863192,1744002851,0,NaN,NaN,NaN,0.0,DK,...,en,NaN,NaN,1,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
6,433,433.0,1611249672,1744002851,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,NaN,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22950,23759,23759.0,1754729867,1754731043,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,NaN,1,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
22951,23760,23760.0,1754732462,1754732462,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,NaN,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
22952,23761,23761.0,1754816467,1754816530,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,NaN,1,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
22953,23762,23762.0,1754816524,1754816524,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,4.560464e+09,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
22954,23763,23763.0,1754825487,1754825487,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,4.521452e+09,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN

DataFrame with NaN values removed and saved to 'user_infos_cleaned.csv'.

In [21]:
user_infos

,id,user_id,created,updated,account_closure_requested,age_group_id,app_version,area_id,cltv,country,...,language,email_temp,mobile_phone_temp,mobile_phone_valid,email_valid,barcode_scanner_ids,receipt_printer_ids,payment_terminal_ids,notifications,favorite_place_ids
0,0,0.0,1571676937,1605685627,0,NaN,NaN,NaN,0.0,DK,...,en,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,1571676937,1744002851,0,12033.0,NaN,11470.0,232.0,DK,...,en,NaN,NaN,0,0,NaN,NaN,NaN,push_orders|push_others|email_orders|email_others,NaN
2,417,417.0,1610542930,1752828166,0,NaN,NaN,NaN,993.0,DK,...,en,NaN,NaN,1,0,NaN,443164|6009243,6009244,push_reviews|push_deals|push_orders|push_other...,NaN
3,423,423.0,1610598865,1744002851,0,NaN,NaN,NaN,0.0,DK,...,en,NaN,NaN,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
4,424,424.0,1610598897,1754741871,0,12032.0,1.659650e+12,11457.0,2039.0,DK,...,en,cashier@lovingloyalty.com,4.522315e+09,0,0,NaN,420542|829147|2388025|2748655|2119442|5935972|...,420539|493523|3291740|5935971|226274|4241778|5...,push_deals|push_orders|push_others|sms_deals|s...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22950,23759,23759.0,1754729867,1754731043,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,NaN,1,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
22951,23760,23760.0,1754732462,1754732462,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,NaN,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
22952,23761,23761.0,1754816467,1754816530,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,NaN,1,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
22953,23762,23762.0,1754816524,1754816524,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,4.560464e+09,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN
22954,23763,23763.0,1754825487,1754825487,0,NaN,NaN,NaN,0.0,DK,...,da,NaN,4.521452e+09,0,0,NaN,NaN,NaN,push_reviews|push_deals|push_orders|push_other...,NaN

##The Digital "Intent" Journey

## The "Basket" & Customization Affinity

##Phase 4: Campaign Effectiveness & "Cannibalization"